[build]
<<<<<<< Updated upstream
  base = "frontend"
  command = "yarn build"
=======
  command = "yarn --cwd frontend build"
>>>>>>> Stashed changes
  publish = "frontend/build"

[functions]
  directory = "frontend/netlify/functions"
