plugins = []
functionsDirectory = "C:\\Users\\gogos\\urban\\frontend\\netlify\\functions"
functionsDirectoryOrigin = "config"
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\gogos\\urban\\frontend\\build"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\gogos\\urban\\frontend"
command = "yarn build"
functions = "C:\\Users\\gogos\\urban\\frontend\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]